// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bookings.sql

package model

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBooking = `-- name: GetBooking :one
SELECT id, car_id, renter_id, start_time, end_time, total_price, status FROM bookings WHERE id=$1
`

type GetBookingRow struct {
	ID         uuid.UUID        `json:"id"`
	CarID      uuid.UUID        `json:"car_id"`
	RenterID   uuid.UUID        `json:"renter_id"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	EndTime    pgtype.Timestamp `json:"end_time"`
	TotalPrice pgtype.Numeric   `json:"total_price"`
	Status     BookingStatus    `json:"status"`
}

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (GetBookingRow, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i GetBookingRow
	err := row.Scan(
		&i.ID,
		&i.CarID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.Status,
	)
	return i, err
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings( car_id, renter_id, start_time, end_time, total_price, status ) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, car_id, renter_id, start_time, end_time, total_price, status, created_at, updated_at
`

type InsertBookingParams struct {
	CarID      uuid.UUID        `json:"car_id"`
	RenterID   uuid.UUID        `json:"renter_id"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	EndTime    pgtype.Timestamp `json:"end_time"`
	TotalPrice pgtype.Numeric   `json:"total_price"`
	Status     BookingStatus    `json:"status"`
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.CarID,
		arg.RenterID,
		arg.StartTime,
		arg.EndTime,
		arg.TotalPrice,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CarID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT id, car_id, renter_id, start_time, end_time, total_price, status FROM bookings ORDER BY start_time
`

type ListBookingsRow struct {
	ID         uuid.UUID        `json:"id"`
	CarID      uuid.UUID        `json:"car_id"`
	RenterID   uuid.UUID        `json:"renter_id"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	EndTime    pgtype.Timestamp `json:"end_time"`
	TotalPrice pgtype.Numeric   `json:"total_price"`
	Status     BookingStatus    `json:"status"`
}

func (q *Queries) ListBookings(ctx context.Context) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CarID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings SET status = $2, start_time = $3, end_time = $4, total_price = $5 WHERE id = $1 RETURNING id, car_id, renter_id, start_time, end_time, total_price, status, created_at, updated_at
`

type UpdateBookingParams struct {
	ID         uuid.UUID        `json:"id"`
	Status     BookingStatus    `json:"status"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	EndTime    pgtype.Timestamp `json:"end_time"`
	TotalPrice pgtype.Numeric   `json:"total_price"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBooking,
		arg.ID,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
		arg.TotalPrice,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CarID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
