// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reviews.sql

package model

import (
	"context"

	"github.com/google/uuid"
)

const listReviews = `-- name: ListReviews :many
SELECT id, reviewer_id, target_id, booking_id, rating, comment FROM reviews ORDER BY updated_at
`

type ListReviewsRow struct {
	ID         uuid.UUID `json:"id"`
	ReviewerID uuid.UUID `json:"reviewer_id"`
	TargetID   uuid.UUID `json:"target_id"`
	BookingID  uuid.UUID `json:"booking_id"`
	Rating     int32     `json:"rating"`
	Comment    string    `json:"comment"`
}

func (q *Queries) ListReviews(ctx context.Context) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewerID,
			&i.TargetID,
			&i.BookingID,
			&i.Rating,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
