// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package model

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMe = `-- name: GetMe :one
SELECT id, first_name, middle_name, last_name, email, password, driver_license, is_owner, is_renter, phone_number, account_number, bank_name, profile_picture  FROM users
WHERE id = $1 LIMIT 1
`

type GetMeRow struct {
	ID             uuid.UUID   `json:"id"`
	FirstName      string      `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	LastName       pgtype.Text `json:"last_name"`
	Email          string      `json:"email"`
	Password       string      `json:"password"`
	DriverLicense  pgtype.Text `json:"driver_license"`
	IsOwner        pgtype.Bool `json:"is_owner"`
	IsRenter       pgtype.Bool `json:"is_renter"`
	PhoneNumber    pgtype.Text `json:"phone_number"`
	AccountNumber  pgtype.Text `json:"account_number"`
	BankName       pgtype.Text `json:"bank_name"`
	ProfilePicture string      `json:"profile_picture"`
}

func (q *Queries) GetMe(ctx context.Context, id uuid.UUID) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, id)
	var i GetMeRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.DriverLicense,
		&i.IsOwner,
		&i.IsRenter,
		&i.PhoneNumber,
		&i.AccountNumber,
		&i.BankName,
		&i.ProfilePicture,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, middle_name, last_name, email,  profile_picture  FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID             uuid.UUID   `json:"id"`
	FirstName      string      `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	LastName       pgtype.Text `json:"last_name"`
	Email          string      `json:"email"`
	ProfilePicture string      `json:"profile_picture"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Email,
		&i.ProfilePicture,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (first_name, email, password, profile_picture) VALUES ( $1, $2, $3, $4) RETURNING id, first_name, middle_name, last_name, email, profile_picture, password, driver_license, phone_number, account_number, bank_name, is_owner, is_renter, created_at, updated_at
`

type InsertUserParams struct {
	FirstName      string `json:"first_name"`
	Email          string `json:"email"`
	Password       string `json:"password"`
	ProfilePicture string `json:"profile_picture"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.FirstName,
		arg.Email,
		arg.Password,
		arg.ProfilePicture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Email,
		&i.ProfilePicture,
		&i.Password,
		&i.DriverLicense,
		&i.PhoneNumber,
		&i.AccountNumber,
		&i.BankName,
		&i.IsOwner,
		&i.IsRenter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT id, first_name, middle_name, last_name, email, driver_license, is_owner, is_renter, phone_number,account_number, bank_name, profile_picture FROM users
ORDER BY email
`

type ListUserRow struct {
	ID             uuid.UUID   `json:"id"`
	FirstName      string      `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	LastName       pgtype.Text `json:"last_name"`
	Email          string      `json:"email"`
	DriverLicense  pgtype.Text `json:"driver_license"`
	IsOwner        pgtype.Bool `json:"is_owner"`
	IsRenter       pgtype.Bool `json:"is_renter"`
	PhoneNumber    pgtype.Text `json:"phone_number"`
	AccountNumber  pgtype.Text `json:"account_number"`
	BankName       pgtype.Text `json:"bank_name"`
	ProfilePicture string      `json:"profile_picture"`
}

func (q *Queries) ListUser(ctx context.Context) ([]ListUserRow, error) {
	rows, err := q.db.Query(ctx, listUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRow
	for rows.Next() {
		var i ListUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.Email,
			&i.DriverLicense,
			&i.IsOwner,
			&i.IsRenter,
			&i.PhoneNumber,
			&i.AccountNumber,
			&i.BankName,
			&i.ProfilePicture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET first_name = $2, middle_name = $3, last_name = $4, email = $5, password = $6, phone_number = $7, account_number = $8, bank_name = $9, driver_license= $10, is_owner=$11, is_renter=$12 , profile_picture=$13 WHERE  id = $1
RETURNING id, first_name, middle_name, last_name, email, profile_picture, password, driver_license, phone_number, account_number, bank_name, is_owner, is_renter, created_at, updated_at
`

type UpdateUserParams struct {
	ID             uuid.UUID   `json:"id"`
	FirstName      string      `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	LastName       pgtype.Text `json:"last_name"`
	Email          string      `json:"email"`
	Password       string      `json:"password"`
	PhoneNumber    pgtype.Text `json:"phone_number"`
	AccountNumber  pgtype.Text `json:"account_number"`
	BankName       pgtype.Text `json:"bank_name"`
	DriverLicense  pgtype.Text `json:"driver_license"`
	IsOwner        pgtype.Bool `json:"is_owner"`
	IsRenter       pgtype.Bool `json:"is_renter"`
	ProfilePicture string      `json:"profile_picture"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.AccountNumber,
		arg.BankName,
		arg.DriverLicense,
		arg.IsOwner,
		arg.IsRenter,
		arg.ProfilePicture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Email,
		&i.ProfilePicture,
		&i.Password,
		&i.DriverLicense,
		&i.PhoneNumber,
		&i.AccountNumber,
		&i.BankName,
		&i.IsOwner,
		&i.IsRenter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
